import { useTranslations } from "next-intl";
import { RootProvider } from "fumadocs-ui/provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./global.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
const t = useTranslations("ui-playground-root-layout");

  return (
    <html lang="en">
      <head>
        <style>{t('styles.font-inter-css-variable', { "interStyleFontFamilyReplaceG": inter.style.fontFamily.replace(/\'/g, "") })}</style>
      </head>
      <body className={`${inter.variable} antialiased`}>
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}
